In [2]:
import os
import re
import yaml
import torch
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display


from dataset import JetSubstructureDataset
from models import JetSubstructureNeqModel
from ensemble import AveragingJetNeqModel, BaggingJetNeqModel, AdaBoostJetNeqModel

In [3]:
dataset_file = "data/processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_truth.z"
dataset_config = "config/yaml_IP_OP_config.yml"

In [5]:
def set_random_seeds(exp_config, cuda=False):
    with open(exp_config, "r") as f:
        config = yaml.safe_load(f)
    # Set random seeds
    random.seed(config["seed"])
    np.random.seed(config["seed"])
    torch.manual_seed(config["seed"])
    os.environ["PYTHONHASHSEED"] = str(config["seed"])
    if cuda:
        torch.cuda.manual_seed_all(config["seed"])
        torch.backends.cudnn.deterministic = True

def load_dataset(dataset_file, dataset_config):
     # Fetch the datasets
    dataset = {}
    dataset["train"] = JetSubstructureDataset(
        dataset_file, dataset_config, split="train"
    )
    # This dataset is so small, we'll just use the training set as the validation set, otherwise we may have too few trainings examples to converge.
    dataset["valid"] = JetSubstructureDataset(
        dataset_file, dataset_config, split="train"
    )
    dataset["test"] = JetSubstructureDataset(
        dataset_file, dataset_config, split="test"
    )
    return dataset

def load_model(exp_config, dataset, checkpoint=None):
    with open(exp_config, "r") as f:
        config = yaml.safe_load(f)
    # Instantiate model
    x, y = dataset["train"][0]
    config["input_length"] = len(x)
    config["output_length"] = len(y)
    print(f"Input length: {config['input_length']}")
    print(f"Output length: {config['output_length']}")

    # Ensemble settings
    quantize_avg = False
    if "quantize_avg" in config:
        quantize_avg = config["quantize_avg"]
    if "post_transform_output" not in config:
        config["post_transform_output"] = True # Default
    if "same_output_scale" not in config:
        config["same_output_scale"] = False # Default
    if "same_input_scale" not in config:
        config["same_input_scale"] = False # Default
    
    if "ensemble_method" in config:
        if config["ensemble_method"] == "averaging":
            print("Averaging ensemble method")
            model = AveragingJetNeqModel(
                config, config["ensemble_size"], quantize_avg=quantize_avg
            )
        elif config["ensemble_method"] == "bagging":
            print("Bagging ensemble method")
            if "independent" not in config:
                config["independent"] = False # Default
            model = BaggingJetNeqModel(
                config,
                config["ensemble_size"],
                quantize_avg=quantize_avg,
                single_model_mode=False,
            )
        elif config["ensemble_method"] == "adaboost":
            print("AdaBoost ensemble method")
            if "independent" not in config:
                config["independent"] = False # Default
            model = AdaBoostJetNeqModel(
                config,
                config["ensemble_size"],
                len(dataset["train"]),
                quantize_avg=quantize_avg,
                single_model_mode=False,
            )
        else:
            raise ValueError(f"Unknown ensemble method: {config['ensemble_method']}")
    else:  # Single model learning
        model = JetSubstructureNeqModel(config)
    if checkpoint is not None:
        print(f"Loading pre-trained checkpoint {checkpoint}")
        checkpoint = torch.load(checkpoint, map_location="cpu")
        model.load_state_dict(checkpoint["model_dict"])

    print(f"Model: {model.__class__.__name__}")

    return model

def compute_cartesian_distance(model):
    """
    Compute Cartesian distance between input sparsity masks of the ensemble members
    """
    ensemble_size = model.num_models
    input_masks = []
    for i in range(ensemble_size):
        mask = model.ensemble[i].module_list[0].fc.mask.mask.numpy()
        input_masks.append(mask)
    input_masks = np.array(input_masks)
    print(f"input masks shape: {input_masks.shape}")
    # print(input_masks)
    cartesian_distances = np.zeros((ensemble_size, ensemble_size))
    for i in range(ensemble_size):
        for j in range(ensemble_size):
            # dist = np.linalg.norm(input_masks[i] - input_masks[j])
            dist = np.sqrt(np.sum(np.abs(input_masks[i] - input_masks[j])))
            # print(f"dist = {dist}")
            cartesian_distances[i, j] = dist
    total_distance = np.sum(cartesian_distances)
    return cartesian_distances, total_distance

def compute_total_cartesian_distance(exp_dir, model_tag=None, checkpoint_file_name="best_accuracy.pth"):
    # Compute for every model in the directory
    dist_arrays = []
    total_dists = []
    models = []
    for model_dir in os.listdir(exp_dir):
        if model_tag not in model_dir:
            continue
        config = os.path.join(exp_dir, model_dir, "hparams.yml")
        ckpt = os.path.join(exp_dir, model_dir, checkpoint_file_name)
        set_random_seeds(config)
        dataset = load_dataset(dataset_file, dataset_config)
        model = load_model(config, dataset, checkpoint=ckpt)
        models.append(model)
        dists, total_dist = compute_cartesian_distance(model)
        total_dists.append(total_dist)
        dist_arrays.append(dists)
    return total_dists, dist_arrays, models

## Averaging Sparsity Masks

In [8]:
config = "./averaging/averaging_small_ensemble_size2/hparams.yml"
ckpt="./averaging/averaging_small_ensemble_size2/best_accuracy.pth"
set_random_seeds(config)
dataset = load_dataset(dataset_file, dataset_config)
model = load_model(config, dataset, checkpoint=ckpt)
dists, total_dist = compute_cartesian_distance(model)

Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/averaging_small_ensemble_size2/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (2, 64, 16)
dist = 0.0
dist = 17.435596466064453
dist = 17.435596466064453
dist = 0.0


In [9]:
dists, total_dist

(array([[ 0.        , 17.43559647],
        [17.43559647,  0.        ]]),
 34.871192932128906)

In [11]:
total_dists, dist_arrays, models = compute_total_cartesian_distance("./averaging", model_tag="averaging_small_ensemble_size")

Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/averaging_small_ensemble_size4/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (4, 64, 16)
dist = 0.0
dist = 17.435596466064453
dist = 17.549928665161133
dist = 18.055469512939453
dist = 17.435596466064453
dist = 0.0
dist = 17.14642906188965
dist = 18.275667190551758
dist = 17.549928665161133
dist = 17.14642906188965
dist = 0.0
dist = 17.77638816833496
dist = 18.055469512939453
dist = 18.275667190551758
dist = 17.77638816833496
dist = 0.0
Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/averaging_small_ensemble_size8/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (8, 64, 16)
dist = 0.0
dist = 17.435596466064453
dist = 17.549928665161133
dist = 18.055469512939453
dist = 17.6068172454834
dist = 17.262676239013672
dist = 18.0
dist = 17.83255386352539
dist = 17.435596466064453
dist = 0.0
dist = 17.146

In [12]:
mdt = zip(models, dist_arrays, total_dists)
mdt = sorted(mdt, key=lambda x: x[0].num_models)

for model, dist_array, total_dist in mdt:
    print(f"Model: {model.__class__.__name__}")
    print(f"Ensemble size: {model.num_models}")
    print(f"Total Cartesian distance: {total_dist}")
    print(dist_array)

Model: AveragingJetNeqModel
Ensemble size: 2
Total Cartesian distance: 34.871192932128906
[[ 0.         17.43559647]
 [17.43559647  0.        ]]
Model: AveragingJetNeqModel
Ensemble size: 4
Total Cartesian distance: 212.4789581298828
[[ 0.         17.43559647 17.54992867 18.05546951]
 [17.43559647  0.         17.14642906 18.27566719]
 [17.54992867 17.14642906  0.         17.77638817]
 [18.05546951 18.27566719 17.77638817  0.        ]]
Model: AveragingJetNeqModel
Ensemble size: 8
Total Cartesian distance: 994.7839431762695
[[ 0.         17.43559647 17.54992867 18.05546951 17.60681725 17.26267624
  18.         17.83255386]
 [17.43559647  0.         17.14642906 18.27566719 17.83255386 17.02938652
  18.05546951 17.88854408]
 [17.54992867 17.14642906  0.         17.77638817 17.83255386 17.77638817
  17.49285507 17.72004509]
 [18.05546951 18.27566719 17.77638817  0.         17.72004509 17.88854408
  17.72004509 18.11077118]
 [17.60681725 17.83255386 17.83255386 17.72004509  0.         17.720

In [13]:
total_dists, dist_arrays, models = compute_total_cartesian_distance("./averaging", model_tag="averaging_medium_ensemble_size")
mdt = zip(models, dist_arrays, total_dists)
mdt = sorted(mdt, key=lambda x: x[0].num_models)

for model, dist_array, total_dist in mdt:
    print(f"Model: {model.__class__.__name__}")
    print(f"Ensemble size: {model.num_models}")
    print(f"Total Cartesian distance: {total_dist}")
    print(dist_array)

Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/averaging_medium_ensemble_size32/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (32, 64, 16)
dist = 0.0
dist = 19.235383987426758
dist = 19.748416900634766
dist = 19.493589401245117
dist = 19.79899024963379
dist = 19.748416900634766
dist = 19.899747848510742
dist = 19.748416900634766
dist = 19.235383987426758
dist = 19.235383987426758
dist = 19.94993782043457
dist = 19.84943389892578
dist = 19.493589401245117
dist = 19.287302017211914
dist = 19.442222595214844
dist = 19.79899024963379
dist = 19.748416900634766
dist = 20.19900894165039
dist = 19.493589401245117
dist = 19.899747848510742
dist = 19.84943389892578
dist = 19.339078903198242
dist = 19.595918655395508
dist = 19.339078903198242
dist = 19.02629852294922
dist = 19.646883010864258
dist = 19.84943389892578
dist = 19.442222595214844
dist = 19.646883010864258
dist = 19.442222595214844
dist = 19.84943389892578
dist

In [6]:
total_dists, dist_arrays, models = compute_total_cartesian_distance("./averaging", model_tag="small_same_output_scale_post_trans_ensemble_size2")
mdt = zip(models, dist_arrays, total_dists)
mdt = sorted(mdt, key=lambda x: x[0].num_models)

for model, dist_array, total_dist in mdt:
    print(f"Model: {model.__class__.__name__}")
    print(f"Ensemble size: {model.num_models}")
    print(f"Total Cartesian distance: {total_dist}")
    print(dist_array)

Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/small_same_output_scale_post_trans_ensemble_size2_seed6/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (2, 64, 16)
Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/small_same_output_scale_post_trans_ensemble_size2_seed1/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (2, 64, 16)
Input length: 16
Output length: 5
Averaging ensemble method
Loading pre-trained checkpoint ./averaging/small_same_output_scale_post_trans_ensemble_size2/best_accuracy.pth
Model: AveragingJetNeqModel
input masks shape: (2, 64, 16)
Model: AveragingJetNeqModel
Ensemble size: 2
Total Cartesian distance: 36.110939025878906
[[ 0.         18.05546951]
 [18.05546951  0.        ]]
Model: AveragingJetNeqModel
Ensemble size: 2
Total Cartesian distance: 35.32704162597656
[[ 0.         17.66352081]
 [17.66352081  0.        ]]
Model: Av